# Generated by Django 6.0.3 on 2026-04-17 07:54

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('chat_type', models.CharField(choices=[('direct', 'Личные сообщения'), ('group', 'Группа')], default='direct', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat',
                'ordering': ['-updated_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Emails_workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'emails_workers',
            },
        ),
        migrations.CreateModel(
            name='Interns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'interns',
            },
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mentors',
            },
        ),
        migrations.CreateModel(
            name='Open1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pa', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'open_1',
            },
        ),
        migrations.CreateModel(
            name='Open3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('pa', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'open_3',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_email', models.EmailField(max_length=254, verbose_name='Email оценивающего')),
                ('target_email', models.EmailField(max_length=254, verbose_name='Email оцениваемого')),
                ('score', models.IntegerField(verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Пользовательское'), ('system', 'Системное')], default='user', max_length=20)),
                ('text', models.TextField(blank=True, default='')),
                ('forwarded_from_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='blog.chat')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_messages', to='blog.users')),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=blog.models.chat_attachment_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='blog.chatmessage')),
            ],
            options={
                'db_table': 'chat_attachment',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_phone', models.CharField(max_length=12)),
                ('fio', models.CharField(max_length=100)),
                ('event_email', models.EmailField(max_length=254, unique=True)),
                ('event_name', models.TextField(blank=True, verbose_name='Название мероприятия')),
                ('field_of_work', models.TextField(blank=True, verbose_name='Область работы')),
                ('organization_of_work', models.TextField(blank=True, verbose_name='Организация работы')),
                ('event_description', models.TextField(blank=True, verbose_name='Описание мероприятия')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_data', to='blog.users')),
            ],
            options={
                'db_table': 'user_data',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('event_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('event_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('field_of_work', models.CharField(max_length=100, verbose_name='Сфера деятельности')),
                ('organization_of_work', models.CharField(max_length=200, verbose_name='Организация')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/4.png', verbose_name='Фото')),
                ('language', models.CharField(default='russian', max_length=20, verbose_name='Язык')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_description', models.TextField(verbose_name='Описание мероприятия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='blog.users')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chats', to='blog.users'),
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='blog.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participants', to='blog.users')),
            ],
            options={
                'db_table': 'chat_participant',
                'unique_together': {('chat', 'user')},
            },
        ),
    ]
