# Generated by Django 6.0.3 on 2026-04-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'email_verification',
            },
        ),
        migrations.DeleteModel(
            name='Open1',
        ),
        migrations.DeleteModel(
            name='Open3',
        ),
    ]
